"aegis_cloud": "azure"
"aegis_data_devices":
- "fs": "ext4"
  "lun": 10
  "mount": "/var/lib/postgresql"
  "name": "pgsql"
- "fs": "xfs"
  "lun": 11
  "mount": "/var/lib/mongodb"
  "name": "mongo"
- "fs": "ext4"
  "lun": 12
  "mount": "/var/lib/redis"
  "name": "redis"
"aegis_raid_luns": []
"aegis_region": "southeastasia"
