apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: lab-restricted
spec:
  containers:
  - name: app
    image: nginx:latest
    # Нет securityContext! Работает от root, не сбрасывает caps.

    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
