# web (frontend): разрешён ТОЛЬКО egress к api на :80. К db напрямую — нельзя.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-egress
  namespace: lab
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: api
    ports:
    - { protocol: TCP, port: 80 }
