apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-db
  namespace: lab
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: fast-ssd # ОШИБКА: несуществующий StorageClass
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
