---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-creds
  namespace: lab
spec:
  encryptedData:
    password: AgCLILJjBys4QO9H7vV1RtAByUiikX5irn248KAwwtUni8aSA8/UnmPKnpGmaHbrF37aHdC9i3hQnG6aybo/C+0k98C5vmUM0/78/ieMQLRY2qY38HhjnXgnJrRB0W6ehqIUuVVRr3QKQP/CTaIyxdpyjXQqj2QqhCXuhAKMw4tF6biZuMojDmz0TEVsoAT6U4EDWdlWiDQtzAL6W0XEDbgOJq3qhM4fQbLOk/GuoPX7kXdRE08PDnyxXSo8sTFmuN9LHk7mCV4cukcp290lGpuCTFJXDub9SkZ1KvXI3t93D9Bp42M/qScRy2IGkFX5xApKStIkyenPaWkdRM9NYhbNmQh+Jry4ye3DwsGtPq62ZA/gJBb9t4D1u8xXYJdaBdphIWqKVWJAAVzLsfZAtrnEHdgVvItWlClKy2rxCz4ag8W42zlDWdTkz9JHsR94qe4QpdyVA+4R39Ak7CafS6bHD9WSsDlH2ilvS61coh7Vmslo/zrG0vCEMIaU/01O2ssChi4s1X23rFybd30tBegiBYmnyr4xWNwVZp9sUOZUkDmowj8CROaDdbbsHphtec2pZh6aUNK85RLcVFazMRqjOzsKz6jlJ8rUNo97CQGg/ko88aQACL93DBPf/0Lz8yWyfcia/XSjTrzCV+YsRije0Vdv6XIM9kBEnj8+gBb9Ks3TTaPcdzr/K3amfERVWq4QJL77WPP1vOjI
    username: AgA4iOfeCNIm5K/NKyad1l3I3UbUSN7IqeuHM7Jv/RYhTlCfuESiCK4GmTeBlBivXd8zllenml7T+Ap2qP+0DqPzUM8iezGaQ4na7U+xiKazEDN1PZdyHpkyhlT8afOjBuL2FJCjTWPTZFZCh+8znOxp3yHIhVs9CCp+uktqE56hGlxd7lfziHEJvmThDl+spkNoxwoMm43JFh0Qc8yXu98gf3K6gfuKygrr82wUoycTsz7c7eYVN9buuOEkDT2/WXoEPgyWNQNS+SCVPv+S7OwOFDsBxXXIPXD9LpCWnEjLAjAbyb1pL97fxB5bVeSe0oVFJ/Okf7wIDbDcf62vCGVbRxoWBCpoyNMnFu7asmljX2dtMChxBuxDJPB5tuBrlfNwYEPv9+yzD6kamCwVrnFeJi+XslXVZwqU2vnL/dvSie8thKdVIO1pOvI+GzskVhSzDPhJz+5ZxbYu7cVF+pt7eq0bLHVC0uBhBq3qq2bWZtXBrXo7k3pfod8a/A53fAydCsjVEQDlZLlhymmFv8atYl0a0s5DBnG2MNGEDYS2Iemw94JN85OGqAHOsmEWTo4LnvwH+nNzVn4yjl50cnolrq4yMYYUNDqph4Dgbkw5e2X5EQCyBgbdqFMkuGw2w9UJYUgkEx7e+I+K25h5wMH10tVI3KXGPvPFqCZREe5FPbJP+Sn1drtBrLRCzsz4DtQ9Fdeqo/uY
  template:
    metadata:
      name: app-creds
      namespace: lab
