apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml
- netpol/00-default-deny.yaml
- netpol/01-allow-dns.yaml
- netpol/02-web.yaml
- netpol/03-api.yaml
- netpol/04-db.yaml
