---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-creds
  namespace: lab
spec:
  encryptedData:
    password: AgAssV4OKdMh5Na7Cy60m9HzCbdssLQBHHNGH/rH8TueoWQ+ajbU0ZoHcAzv0gZYJz1vvJvW5bebQsfRBmKTMQ466Lrw1kjOj47u+jER3Y6Ad/C6bdsfSe63sP3pnBK1nwQp8dW1w9USVofJBbewGWtOnG/O8rbiGmpPslRmQO0iMBFfFB5GrCwo0O2OD5wu1y4xyoyurdLdRG9OHvrRtgNBLzFbHQ8LHkc+U9RJKzloL+nVATkEYAhhcPQTo/3PsA0/v01ckvIi7iy6RKqKZbvJJoH4TXTrrzW3qQFR2kvUihyzopTBwBKtKblL4WzPakFvkG3hlzmUatVwcnFNoXQ2heMFJhE+vKL3FdEYxVQPN3skLZ8GYXKQ0x0bbCwkIsafNUKKMQPHDbkvJ7jV/vOTjfGsZf0CbaQtvBbdBoVpQNXH2KnBrY1nZQYRRWgJiJqtmMhXHvPCqxn3yCucgCjcfxYLehaDi9vK/gR65kOld87GDKROCJQp6tYIHdW8NBklk7vsAPNOUfBHsYe1FQ7BbrsIRMP8vAfVqJfr/gi30GgdbNtZpuebhY7QpCkiFY5kj3LlJKUlvgkZe/sUgGb0Wfyd4Iu3SEY2RHY/SKV2oQ/cAFqkHWRHHgcV4J9fC1Hk4j6Y7RE6TymFHcr3EmfXPAhqOwUa7dpjKHnMPw6OEORVqCgyxNBVaoVlGG+W47YQ7v75BqUp5XtI
    username: AgBNAAjZxuZTVeLm/oUhVQ3be+EJmP51Qkye28JeOnbRAjAgAZdgWy9GIFMMN7zHPunxF60Rg+6LB7lrN3QfiXXdtaaZbbqEzNZxMIT4mCk5EYE/TYF0rHZkHB8BD2APyTiJXbeVVCDvDFDTdVZvl2+shOqNpwPfk4/1VsvSBFk7KU22rLLZ+IcqEV6eRKjuEfpOVx5OcsctkUJUFXx3SEOme60oFHslyyBHBor3wehwSLWpQvlncekb543GTwSE1qLK55T9aCwnj3jO0ZS4Y/p81sRwQcgsrc/FScugl5yNxSG0pzSAeoDEDOwGazDOAFqdpluTjTdLtUKQpS4HT4spPGk+4qE7ign++LJW69UFoJcIin65bsN5Tu+ib8cPyDpp+9W9NdC9VocVGVE9YzrkHehxLP5RuNI1wuC7/75gEfbXv4rBIHJvkdrSGCFr9U0DH07AZ0ksSufJ0xG4y5aZk4VsWgBteq0Xbc7gMCIwmmPCMqXa8jGezv+aZWfzgZaQTckN1zGd63/Y5jr9J8HkIhgvzBuulXLWsWgDU7gqCzaTvNOV/85XeYNvqeDdn+NaXgCcpF4oE7DoE4op0ptty3dxUBc6OOgCHZ6RXimnMz66fRCsvscT8Quwr91g5q/ejw2B54scvUV+Jh3+J/okLChm3aE2qMIqgeWf2n8o9dbvxrfY6J31GfwCB1tdY0a3tTPetA3t
  template:
    metadata:
      name: app-creds
      namespace: lab
